### PR TITLE
allow sequel 5.x versions

### PR DESCRIPTION
**Pull request by bgentry**
@nhmood this updates [your PR](https://github.com/mlen/sequel_secure_password/pull/16) to include a Gemspec fix to allow Sequel 5.x versions.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Duplicate of #1 :confused:

**Comment by bgentry** [comment]
oops, sorry, didn't see that. Do we know for sure whether this still works on 4.x?

**Comment by AlexWayfer** [comment]
> Do we know for sure whether this still works on 4.x?

Good question. I decided to do it just in case, but now I've checked this — it works with Sequel 4.

I returned the minimal version, thank you.

**Comment by nhmood** [comment]
Addressed by #1 , sorry for the delay!

**Pull request closed without merging**
